# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='urlname',
            field=models.CharField(default=datetime.datetime(2016, 6, 24, 17, 41, 34, 635976, tzinfo=utc), max_length=48),
            preserve_default=False,
        ),
    ]
