# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userrelationships'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationships',
            unique_together=set([('follower_id', 'following_id')]),
        ),
    ]
