# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20160707_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Guild Join Date')),
            ],
        ),
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('guild_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('guild_name', models.CharField(max_length=64)),
                ('date', models.DateTimeField(verbose_name='Guild Creation Date')),
                ('guild_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='guild_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Guilds'),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together=set([('user_id', 'guild_id')]),
        ),
    ]
