# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160712_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuildMembership',
            new_name='GuildMemberships',
        ),
    ]
