# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160712_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='guild_description',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
    ]
