# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160715_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilds',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
