# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_auto_20160715_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='allowed_users',
            field=models.ManyToManyField(related_name='_articles_allowed_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
