# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160718_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Article read permissions are public'),
            preserve_default=False,
        ),
    ]
