# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_articles_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public visibility'),
        ),
    ]
