# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.models import User

class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Publication Date')),
                ('article_text', models.TextField()),
                ('subject', models.CharField(max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User')),
            ],
        ),
    ]
